
- name: Add containerd
  apt:
    name: containerd
    state: latest
    cache_valid_time: '3600'

- name: Ensure crictl config
  copy:
    content: |
      runtime-endpoint: "unix:///run/containerd/containerd.sock"
      image-endpoint: ""
      timeout: 0
      debug: false
      pull-image-on-create: false
      disable-pull-on-run: false
    dest: /etc/crictl.yaml
