- name: Ensure facts
  hosts: all
  tasks:
    - setup:
      register: _facts

    - copy:
        content: '{{ _facts|to_nice_json() }}'
        dest: /tmp/facts.yml


- name: Install kube
  hosts: all
  tags: kubernetes

  roles:
    - name: local.powerline
      tags: powerline
    - name: local.binenv
      tags: binenv
    - name: local.kube-preflight
      tags: containerd
    - name: local.kubectl-utils
      tags: utils
    - name: local.kube-apiserver
      tags: apiserver
      when: kubeadm_is_master
    - name: local.kube-worker
      tags: worker
      when: kubeadm_is_worker


- name: Setup cilium
  hosts: master1
  tags: cilium

  roles:
    - name: local.cilium
      tags: cilium
