
kube_apiserver_advertise_address: '{{ ansible_default_ipv4.address }}'
kube_apiserver_bind_port: '{{ kube_apiserver_port }}'

# change this
# kubeadm certs certificate-key
kube_certificate_encryption_keys: '7c59776340197730155d2d9b175b0ff1e65ca73d58f273255e33ea456122d735'

kube_apiserver_host: 127.0.0.1
kube_apiserver_port: 6443

kube_cluster_cidr: 172.16.0.0/16
kube_service_cidr: 172.18.0.0/16

kube_advertise_address: '{{ ansible_default_ipv4.address }}'
kubernetes_join_token: 42
kubernetes_ca_cert_hash: 0

kube_node_name: '{{ inventory_hostname }}'

kubernetes_version: v1.24.1
kubeadm_init_dir: /root/kubeadm-init

# Add extra parameters to kubeadm in you group_vars
kubeadm_extra_params: ''
kube_dns_domain: cluster.local

# Time to live for Join token
kubeadm_token_ttl: 60s

# Name of first kube apiserver
# kube_first_apiserver_name: None


# stop Ansible playbook before applying kubeadm init
kubeadm_stop_before_run: false
